# Site settings
title: Dennis Wong
# general_email: your_general_email@gmail.com
academic_email: cwong@mpu.edu.mo

description: > # this means to ignore newlines until "baseurl:"
  This is homepage of Assoc. Prof. Dennis Wong, a faculty member at Macau Polytechnic University.

baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "https://retrozhou.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
# github_username: github_username
# linkedin_username: linkedin_username
# facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
# permalink: blog/:year/:month/:title