# Site settings
title: Dennis Wong
academic_email: cwong@mpu.edu.mo

description: > # this means to ignore newlines until "baseurl:"
  This is homepage of Assoc. Prof. Dennis Wong at Macau Polytechnic University.

baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "https://retrozhou.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax
